services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tourplaner-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - tp-network
    volumes:
      - ./database/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  

  backend: 
    build: ./backend
    container_name: tourplaner_api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tp-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PWD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}


  frontend:
    build: ./frontend
    container_name: tourplaner_frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - tp-network


networks:
  tp-network:
    driver: bridge
    