package at.s_sal.tourplaner.helper.type;

public enum IErrorCodes {
    INVALID_USER_CREDENTIAL,
    USER_CREDENTIALS_TAKEN,
    TOUR_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    NO_RESOURCES_FOUND, LOG_NOT_FOUND, EXTERNAL_API_ERROR, NO_PERMISSION_TO_ACCESS_RESOURCE
}
