spring:
  application:
    name: tourplaner
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  mvc:
    problemdetails:
      enabled: true



